version: '3.8'

services:
  app:
    image: mitch-b/maintenancelog:latest
    container_name: maintenancelog-app
    build:
      context: src
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: ${MAINTENANCELOG_TZ:-America/Chicago}
      MAINTENANCELOGSETTINGS__DATABASE__DBPROVIDER: mssql
      MAINTENANCELOGSETTINGS__DATABASE__HOST: db
      MAINTENANCELOGSETTINGS__DATABASE__NAME: ${MAINTENANCELOG_DATABASE_NAME:-MaintenanceLog}
      MAINTENANCELOGSETTINGS__DATABASE__USER: ${MAINTENANCELOG_DATABASE_USER:-sa}
      MAINTENANCELOGSETTINGS__DATABASE__PASSWORD: ${MAINTENANCELOG_DATABASE_PASSWORD:-This is publ1c, so whatever works!}
      MAINTENANCELOGSETTINGS__DATABASE__DEVDROPDATABASE: "false"
    ports:
      - ${MAINTENANCELOG_PORT:-8080}:8080
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: maintenancelog-sql
    environment:
      MSSQL_SA_PASSWORD: ${MAINTENANCELOG_DATABASE_PASSWORD:-This is publ1c, so whatever works!}
      ACCEPT_EULA: Y
    volumes:
      - ./.devcontainer/mssql/data:/var/opt/mssql/data
      - ./.devcontainer/mssql/log:/var/opt/mssql/log
      - ./.devcontainer/mssql/secrets:/var/opt/mssql/secrets
    ports:
      - ${MAINTENANCELOG_DATABASE_PORT:-1433}:1433
