version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
    environment:
      - DATABASE_URL=Server=db;Database=MaintenanceLog;User Id=sa;Password=${MAINTENANCELOG_DATABASE_PASSWORD:-This is publ1c, so whatever works!}

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: maintenancelog-sql
    user: root
    environment:
      MSSQL_SA_PASSWORD: ${MAINTENANCELOG_DATABASE_PASSWORD:-This is publ1c, so whatever works!}
      ACCEPT_EULA: Y
    volumes:
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/secrets
    ports:
      - ${MAINTENANCELOG_DATABASE_PORT:-1433}:1433 
